### PR TITLE
Update Ex Nihilo to 2.0.2.6

### PR DESCRIPTION
**Pull request by Irgendwer01**

### CODE REVIEW

**Comment by remplerus** [comment]
dont forget to update mods.toml to use newer version too
instead of hardcoding, use ,) to use newer version too

**Review by remplerus — APPROVED** [review]

**Comment by kreezxil** [comment]
if he doesn't release a new build by Monday, please add this and a copy of the binary to my fork of the project, I'll release it under an experimental page using the same name space. I'm thinking he used open licenses for a reason.

**Comment by Irgendwer01** [comment]
@remplerus Done

**Comment by lazynessmind** [comment]
What did I lost here? Im just porting my mods to kotlin lol

**Comment by lazynessmind** [comment]
Fixed in 43c481c and 5e87f71.
In my tests, everything is working.

And is uploaded to Curse

**Comment by Irgendwer01** [comment]
@lazynessmind Why locking the Mod to just work with one specific version of Ex Nihilo Sequentia?

**Comment by lazynessmind** [comment]
Only safety reasons. I.E: If Nova make a change to the API that can break my mod, I can found the bugs first and update the mod without any bug reports.

**Comment by lazynessmind** [comment]
Only safety reasons. I.E: If Nova make a change to the API that can break my mod, I can found the bugs first and update the mod without any bug reports.
So if the user is restricted to a specific version, they will not encountered any bugs until I test and upgrade the mod to the new version of exnihilo

**Comment by remplerus** [comment]
there wont be any major changes to the api till 1.17, just some render updates and maybe new textures.

**Comment by lazynessmind** [comment]
> there wont be any major changes to the api till 1.17, just some render updates and maybe new textures.

@remplerus ok 👌
Updating it...

**Pull request closed without merging**
